FROM python:3-alpine
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
EXPOSE 5000

ENV FLASK_ENV development
ENV FLASK_DEBUG 1
CMD flask run -h 0.0.0.0 -p 5000